### ISSUE TITLE
Missing box weapons

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-Strat_Tester#16]
Hello,

On Call of the Dead (and maybe Shangri-la and other maps, not sure), some weapons are missing from the mystery box : AUG, Commando, FAMAS, Galil, CZ75x2 and Python.
It's not a big deal, but it prevents from testing what an actual round could be, because the wonder weapon averages are broken.

Thanks

**Comment by TTS4life** [comment]
Issue was the `_zombiemode_weapons.gsc` used in the project came from a trade strat mod that had certain weapons removed for some reason instead of directly from source ([wonder who let that slip through](https://github.com/5and5/BO1-Strat_Tester/commit/d6d3087de59d417e778e2b900076ef738b493184)) It took an embarrassingly long time to figure out. Implemented for next release. In the meantime you can visit my fork to download a version with the fixes but I'm going to work on a couple of things over the next bit here now that some bugs/feature requests have popped up.
