### ISSUE TITLE
Dogs not taken into account for SPH on Der Riese

### ISSUE THREAD

**Issue by llPh3NiXll** [5and5/BO1-Strat_Tester#21]
Hello,

When killing dogs on Der Riese, it seems like the SPH does not take into account these kills.

Video here : https://www.youtube.com/watch?v=z5tJIiLK5Ng

Thanks !

**Comment by TTS4life** [comment]
Video provided is from an older version of Strat Tester. The current version properly counts dogs as part of the Seconds Per Horde (see video)

https://user-images.githubusercontent.com/60669844/211944039-c29618a8-12c3-412f-95d6-addbf0b2d1c4.mp4

I recommended to install the latest version in order to have proper working dogs. The patch version is wildly out-of-date and not actively maintained (and I have no plans on maintaining it at this time, and I think it is much less work to install the game_mod version because you don't have to keep swapping out your `common_zombie_patch.ff`).

Those who are still using the patch version and want to swap over to game_mod can use the video tutorial I made as a guide.
https://youtu.be/rTJs7evNRXo

Going to mark this as closed since it is not an issue on current version, but thanks for reaching out!
