### ISSUE TITLE
select weapon option gone

### ISSUE THREAD

**Issue by hgmrick** [5and5/BO1-Strat_Tester#6]
![20220215033151_1](https://user-images.githubusercontent.com/80927771/154005904-3d241237-8dbb-494c-80bf-dc5eb6edd59d.jpg)

**Comment by TTS4life** [comment]
It appears that you are using the `common_zombie_patch.ff` version of the mod which was built on Jun 6th on commit 5f5dbc7cb95d384b173e0751203ceb8fbbf9b384, and is missing any new features we've added since. Gonna ask @5and5 to make a new version of the patch with the latest updates for those who want it, but I recommend personally setting up the game_mod version of the mod. To do so, do the following:

Download game_mod and download the `game_mod.zip` file in the Assets section 
https://github.com/Nukem9/LinkerMod/releases/tag/v1.3.2

Extract the contents of the zip to the root of your BO1 folder. If `BO_Mods.bat` is next to the executables for the game, you're on the right track.

![image](https://user-images.githubusercontent.com/60669844/154386847-b8789e1e-a12a-4b3e-bcb0-5ec316ad2614.png)

then, create a `mods` folder, and go into it.

Click here to download the latest version of the mod https://github.com/5and5/BO1-Strat_Tester/archive/refs/heads/main.zip

Open that zip, and put `BO1-Strat_Tester-main`  into the `mods` folder (You can rename the folder if you wish).

Run `BO_mods.bat` and allow to run as admin

There should now be a `MODS` option on the TV. Select it and click on the BO1 Strat Tester folder.

Happy strat testing!

I intend to upload a video going through the install process after we get a release sorted. If you have troubles getting everything setup in the meantime let me know on Discord.
